config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  get '/users/:user_id/posts/:id/like', to: 'posts#like', as: 'like_post'
  # Defines the root path route ("/")
  root "users#index", as: :index
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    # Users can read anything (posts, comments, likes) except destroy
    can :read, :all
    can :create, :all

    can :destroy, Post, author: user
    can :destroy, Comment, author: user

    # Admins can destroy anything
    return unless user.role == 'admin'

    can :destroy, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post, counter_cache: :comments_counter

  before_create :increment_user_commentcounter
  before_destroy :decrement_user_commentcounter

  private

  def increment_user_commentcounter
    post.increment(:comments_counter).save
  end

  def decrement_user_commentcounter
    post.decrement(:comments_counter).save
  end

  # VALIDATIONS
  # text must not be blank. and must not exceed 100 characters.
  validates :text, presence: true, length: { maximum: 100 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post, counter_cache: :likes_counter

  before_create :increment_user_likecounter
  before_destroy :decrement_user_likecounter

  private

  def increment_user_likecounter
    post.increment(:likes_counter).save
  end

  def decrement_user_likecounter
    post.decrement(:likes_counter).save
  end

  # VALIDATIONS
  # should validate uniqueness of author_id scoped to post_id
  validates :author_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, dependent: :destroy, counter_cache: :comments_counter
  has_many :likes, dependent: :destroy, counter_cache: :likes_counter

  before_create :increment_user_postcounter
  before_destroy :decrement_user_postcounter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def likes_counter
    likes.count
  end

  def comments_counter
    comments.count
  end

  private

  def increment_user_postcounter
    author.increment(:posts_counter).save
  end

  def decrement_user_postcounter
    author.decrement(:posts_counter).save
  end

  # VALIDATIONS
  # Title must not be blank.
  validates :title, presence: true
  # Title must not exceed 250 characters.
  validates :title, length: { maximum: 250 }
  # CommentsCounter must be an integer greater than or equal to zero.
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  # LikesCounter must be an integer greater than or equal to zero.
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  # name must be present
  validates :name, presence: true

  # posts_count must be a integer and greater than or equal to 0
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post = Post.find(params[:post_id])
    return unless @comment.save

    redirect_to user_posts_path(params[:user_id], params[:post_id])
  end

  def destroy
    comment = Comment.find(params[:id]) || not_found

    respond_to do |format|
      if comment.destroy
        # Successfully deleted the record
        flash[:success] = 'Comment deleted successfully'
      else
        # Failed to delete the record
        flash.now[:error] = 'Error: Comment could not be deleted'
      end
      format.html { redirect_to user_posts_path(params[:user_id], params[:post_id]) }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesCounter < ApplicationController
  def create
    @like = current_user.likes.new
    @like.post_id = params[:id]
    if @like.save
      redirect_to user_post_path(@like.post.author_id, @like.post), notice: 'like added successfully'
    else
      @post = Post.find(params[:id])
      redirect_to user_post_path(@post.author_id, @post), notice: 'Failed to add a like'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @user = User.find_by_id(params[:user_id]) || not_found
  end

  def show
    # use includes to avoid n+1 queries
    # find the user by id and include posts and comments
    @user = User.includes(:posts, posts: [:comments])
      .where(posts: { id: params[:id] })
      .find_by_id(params[:user_id]) || not_found
  end

  def new
    post = Post.new
    user = current_user
    post.author = user
    respond_to do |format|
      format.html { render :new, locals: { post:, user: } }
    end
  end

  def create
    @user = current_user
    @post = Post.new(post_params)
    @post.author = @user

    respond_to do |format|
      if @post.save
        flash[:success] = 'Post saved successfully'
        # redirect to root
        format.html { redirect_to user_posts_path(@user) }
      else
        flash[:error] = 'Post failed to save'
        format.html { render :new, locals: { post: @post, user: @user } }
      end
    end
  end

  def destroy
    # use includes to avoid n+1 queries
    post = Post.includes(:comments, :likes).find_by_id(params[:id]) || not_found

    post.comments.destroy_all
    post.likes.destroy_all

    respond_to do |format|
      if post.destroy
        # Successfully deleted the record
        flash[:success] = 'Post deleted successfully'
        format.html { redirect_to "/users/#{current_user.id}/posts" }
      else
        # Failed to delete the record
        flash.now[:error] = 'Error: Post could not be deleted'
        format.html { render :show }
      end
    end
  end

  def like
    # @post = Post.find(params[:id])
    @like = current_user.likes.new
    @like.post_id = params[:id]

    # check if user already liked the post
    return unless @like.save

    if @like.save
      redirect_to user_post_path(@like.post.author_id, @like.post), notice: 'like added successfully'
    else
      redirect_to user_post_path(@post.author_id, @post), notice: 'Failed to add a like'
    end
  end

  private

  def post_params
    params.require(:post).permit(:author_id, :title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @user = current_user
  end

  def show
    @user = User.find_by_id(params[:id]) || not_found
    @posts = @user.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1 class='text-[3em] text-slate=500 text-center'>New Comment</h1>

<%= form_with model: [@user, @post, @comment], url: user_post_comments_path, class: 'flex flex-col m-auto' do |form| %>
    <div class='flex flex-col my-5 m-auto'>
      <%= form.text_area :text, required: true, autofocus: true, placeholder: 'Text...', class: 'text-[2em] w-[60vw] bg-slate-300 mx-3 text-slate-700 font-semibold inline-block' %>
    </div>
    <%= form.submit "submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body>
    <header>
        <% # navigation with log in %>
        <nav class="flex justify-between p-2 bg-slate-200">
          <ul class="flex">
            <li class="mr-6 text-[2em]"><%= link_to "Home", index_path %></li>
            <li class="mr-6 text-[2em]"><%= link_to "Users", users_path %></li>
            <%if user_signed_in? %>
              <li class="mr-6 text-[2em]"><%= link_to "My Posts", user_posts_path(current_user.id) %></li>
            <% end %>
          </ul>
          <ul class="flex">
            <% if user_signed_in? %>
              <li class="mr-6 text-[2em]"><%= link_to "Edit", edit_user_registration_path %></li>
              <li class="mr-6 text-[2em]">
                <%= form_with(url: destroy_user_session_path, method: :delete) do |form| %>
                  <%= form.submit 'Sign Out' %>
                <% end %>
              </li>
            <% else %>
              <li class="mr-6 text-[2em]"><%= link_to "Log in", new_user_session_path %></li>
              <li class="mr-6 text-[2em]"><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </nav>
    </header>
    
    <main class="container p-5 flex-col">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<%= render 'shared/user', user: @user%>

<%= render partial: 'shared/post', collection: @posts[0...3], locals: { truncate: true, comments: true }%>

<div class='flex justify-around'>
  <%= link_to 'Pagination', user_posts_path(user_id: @user.id), class: 'm-auto p-3 text-[1.5em] font-bold bg-slate-600 hover:bg-slate-900 hover:text-white' %>
<div>

app/views/posts/new.html.erb
<h1 class='text-[3em] text-slate=500 text-center'>New Post</h1>

<%= form_with model: post, url: user_posts_path(user), class: 'flex flex-col m-auto' do |form| %>
    <div class='flex flex-col m-auto justify-center'>
      <%= form.text_field :title, required: true, autofocus: true, placeholder: 'Title', class: 'text-[2em] w-[60vw] bg-slate-300 mx-3 text-slate-700 font-semibold inline-block' %>
    </div>

    <div class='flex flex-col my-5 m-auto'>
      <%= form.text_area :text, required: true, autofocus: true, placeholder: 'Text...', class: 'text-[2em] w-[60vw] bg-slate-300 mx-3 text-slate-700 font-semibold inline-block' %>
    </div>

    <%= form.submit "submit" %>
<% end %>

app/views/posts/show.html.erb
<%= render partial: 'shared/post', locals: { post: @post, truncate: false, comments: true }%>

<% if can? :destroy, @post %>
  <%= button_to 'Edit', user_post_path, method: :update, data: { confirm: 'Are you sure?' }  %>
  <%= button_to 'Delete', user_post_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded justify-end' %>
<% end %>

app/views/shared/_comment.erb
<div class='flex'>
    <h4 class='text-[1em] font-bold'> <%= comment.author.name %> : </h4>
    <p class='text-[1em] mx-2'> <%= comment.text %> </p>
</div>

app/views/shared/_comment.html.erb
<div class='flex'>
    <h4 class='text-[1em] font-bold'> <%= comment.author.name %> : </h4>
    <p class='text-[1em] mx-2'> <%= comment.text %> </p>

    <% if can? :destroy, comment %>
        <%= button_to 'Delete', user_post_comment_path(comment.author, comment.post, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded justify-end' %>
    <% end %>
</div>

app/views/shared/_post.erb
<% text = post.text %>
<% if truncate %>
    <%text = post.text.truncate(100)%>
<% end %>

<div class='my-5'>
    <div class='relative m-10 p-5 z-[2] bg-gray-300 rounded-3xl min-h-[15vh]'>
        <% if !truncate %>
            <div class='flex flex-row-reverse'>
                <p class='text-[1em] mx-3 text-slate-700 font-semibold inline-block'>Likes: <%= post.likes_counter %></p>
                <p class='text-[1em] mx-3 text-slate-700 font-semibold inline-block'>Comments: <%= post.comments_counter %></p>
            </div>
        <% end %>

        <a href='/users/<%= @user.id %>/posts/<%= post.id %>'>
            <h1 class='text-[2em] text-slate-700 font-semibold underline'><%= post.title %></h1>
        </a>
        <p class='text-[1em] py-5 px-3'><%= text %></p>

        <% if truncate %>
            <div class='flex flex-row-reverse'>
                <p class='text-[1em] mx-3 text-slate-700 font-semibold inline-block'>Likes: <%= post.likes_counter %></p>
                <p class='text-[1em] mx-3 text-slate-700 font-semibold inline-block'>Comments: <%= post.comments_counter %></p>
            </div>
        <% end %>
    </div>

    <% if comments %>
        <div class='mx-10 p-8 z-[1] bg-gray-100 rounded-3xl min-h-[15vh] translate-y-[-4rem]'>
            <%= render partial: 'shared/comment', collection: post.comments%>
        </div>
    <% end %>
</div>

app/views/shared/_post.html.erb
<% text = post.text %>
<% if truncate %>
    <%text = post.text.truncate(100)%>
<% end %>

<div class='my-5 post'>
    <div class='relative m-10 p-5 z-[2] bg-gray-300 rounded-3xl min-h-[15vh]'>
        <% if !truncate %>
            <div class='flex flex-row-reverse'>
                <p class='text-[1em] mx-3 text-slate-700 font-semibold inline-block'>Likes: <%= post.likes_counter %></p>
                <p class='text-[1em] mx-3 text-slate-700 font-semibold inline-block'>Comments: <%= post.comments_counter %></p>
            </div>

            <%= link_to 'Like', like_post_url, class: 'text-blue-700 text-[1.3em]' %>
            <%= link_to 'Comment', new_user_post_comment_path(user_id: @user.id, post_id: post.id), class: 'm-auto mx-10 text-red-700 text-[1.3em]'%>
        <% end %>

        <a href='/users/<%= @user.id %>/posts/<%= post.id %>'>
            <h1 class='text-[2em] text-slate-700 font-semibold underline'><%= post.title %></h1>
        </a>
        <p class='text-[1em] py-5 px-3'><%= text %></p>

        <% if truncate %>
            <div class='flex flex-row-reverse'>
                <p class='text-[1em] mx-3 text-slate-700 font-semibold inline-block'>Likes: <%= post.likes_counter %></p>
                <p class='text-[1em] mx-3 text-slate-700 font-semibold inline-block'>Comments: <%= post.comments_counter %></p>
            </div>
        <% end %>
    </div>

    <% if comments %>
        <div class='mx-10 p-8 z-[1] bg-gray-100 rounded-3xl min-h-[15vh] translate-y-[-4rem]'>
            <%= render partial: 'shared/comment', collection: post.comments%>
        </div>
    <% elsif post.comments.count > 0 %>
        <div class='mx-10 p-8 z-[1] bg-gray-100 rounded-3xl min-h-[15vh] translate-y-[-4rem]'>
            <%= render partial: 'shared/comment', locals: { comment: post.comments.first } %>
        </div>
    <% end %>
</div>

app/views/shared/_user.erb
<div class="flex items-center w-full p-2 px-5 rounded-3xl my-10 bg-gray-300">
  <%= image_tag(!user.photo ? 'avatar.png' : user.photo, alt: 'Image Description', class: 'h-[15vh]') %>

  <a class="user--info px-10 py-4 mx-10 flex flex-col justify-center bg-slate-100 w-full" title="view user details" href="/users/<%= user.id %>">
    <h2 class="text-[4em] font-bold"><%= user.name %></h2>
      
    <p class="text-25 font-bold self-end inline-block">Number of posts: <%= user.posts_counter%> </p>
  </a>
</div>

app/views/shared/_user.html.erb
<div class="flex items-center w-full p-2 px-5 rounded-3xl my-10 bg-gray-300">
  <%= image_tag(!user.photo ? 'avatar.png' : user.photo, alt: 'Image Description', class: 'h-[15vh]') %>

  <a class="user--info px-10 py-4 mx-10 flex flex-col justify-center bg-slate-100 w-full" title="view user details" href="/users/<%= user.id %>">
    <h2 class="text-[4em] font-bold"><%= user.name %></h2>
      
    <p class="text-25 font-bold self-end inline-block">Number of posts: <%= user.posts_counter%> </p>
  </a>
</div>

app/views/users/index.html.erb
<%= link_to 'New Post', new_user_post_path(user_id: @user.id) %>

<%= render partial: 'shared/user', collection: @users %>

app/views/users/show.html.erb
<%= render 'shared/user', user: @user%>

<article>
    <h2 class="text-[3em] font-bold">Bio</h2>
    <p class="text-[1.5em] border-l-[10px] px-2 border-blue-200 self-end inline-block"> <%= @user.bio %> </p>
</article>

<%= render partial: 'shared/post', collection: @posts, locals: { truncate: true, comments: false}%>

<div class='flex justify-around'>
  <%= link_to 'See All Posts', user_posts_path(user_id: @user.id), class: 'm-auto p-3 text-[1.5em] font-bold bg-slate-600 hover:bg-slate-900 hover:text-white' %>
<div>